-- ============================================================
-- FestasBV — Histórico de alterações (auditoria append-only)
-- Projeto: diogoandrefsilva-personalapps-database  ·  schema: festasbv
-- Correr no SQL Editor do Supabase.
--
-- Porquê uma tabela e não um trigger nas tabelas presencas/convidados:
-- o sbGuardarEvento faz DELETE-all + INSERT a cada gravação (snapshot),
-- por isso um trigger nessas tabelas encheria o log de ruído. Esta tabela
-- é escrita pela APP no momento da ação real (marcar presença, add/editar/
-- remover convidado), logo cada linha = uma ação verdadeira, com autor e hora.
--
-- O mesmo INSERT alimenta a notificação do Telegram (Database Webhook em
-- historico/INSERT -> Edge Function). Ver LEIA-ME-telegram.md.
--
-- NOTA: o schema 'festasbv' já está exposto na Data API e os GRANTs de
-- ALTER DEFAULT PRIVILEGES do DDL original já cobrem tabelas novas. Ainda
-- assim, os GRANTs abaixo são repetidos por segurança (são idempotentes).
-- ============================================================

CREATE TABLE IF NOT EXISTS festasbv.historico (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  evento_id   BIGINT REFERENCES festasbv.eventos(id) ON DELETE CASCADE,
  ts          TIMESTAMPTZ NOT NULL DEFAULT now(),   -- = "modificado_em"
  autor_email TEXT NOT NULL,                        -- = "modificado_por" (quem estava em sessão)
  autor_amigo TEXT,                                 -- nome do amigo ligado à conta (null se admin sem membro)
  tipo        TEXT NOT NULL,                        -- 'presenca' | 'convidado'
  accao       TEXT NOT NULL,                        -- presenca: marcou/mudou/removeu · convidado: adicionou/editou/removeu
  alvo        TEXT NOT NULL,                        -- membro (presença) ou nome do convidado
  detalhe     JSONB NOT NULL DEFAULT '{}'::jsonb    -- {dia, ref, modo, membro, de, para, ...}
);

CREATE INDEX IF NOT EXISTS historico_evento_ts_idx
  ON festasbv.historico (evento_id, ts DESC);

-- ─── GRANTs (sem isto: HTTP 403 / 42501) ─────────────────────
GRANT USAGE ON SCHEMA festasbv TO anon, authenticated;
GRANT ALL ON festasbv.historico TO anon, authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA festasbv TO anon, authenticated;

-- ─── RLS ─────────────────────────────────────────────────────
ALTER TABLE festasbv.historico ENABLE ROW LEVEL SECURITY;

-- Ler: qualquer utilizador aprovado vê o histórico (transparência).
CREATE POLICY hist_select ON festasbv.historico
  FOR SELECT TO authenticated
  USING (auth.email() IN (SELECT email FROM festasbv.allowed_users));

-- Inserir: aprovados, mas SÓ em nome do próprio email (anti-falsificação).
CREATE POLICY hist_insert ON festasbv.historico
  FOR INSERT TO authenticated
  WITH CHECK (
    auth.email() IN (SELECT email FROM festasbv.allowed_users)
    AND autor_email = auth.email()
  );

-- Apagar: só o admin (limpeza pontual). Sem UPDATE: o log é imutável.
CREATE POLICY hist_admin_del ON festasbv.historico
  FOR DELETE TO authenticated
  USING (auth.email() = 'diogo.andre.f.silva@gmail.com');

-- ============================================================
-- Pronto. Não é preciso mexer em "Exposed schemas" (festasbv já lá está).
-- A app já escreve aqui via sbLog() e lê no bloco "Histórico" das Definições.
-- ============================================================
