-- =====================================================================
-- FestasBV — Migração: Categorias de artigos (festasbv.categorias +
-- festasbv.artigo_categorias)
-- Correr no SQL Editor do Supabase (projeto festasbv).
-- É IDEMPOTENTE: pode ser corrido mais que uma vez sem erro.
-- Depende de: functions.sql (is_allowed/is_admin).
-- Ordem: schema.sql -> functions.sql -> policies.sql -> shoplist.sql ->
--        stock.sql -> ESTE.
--
-- O QUE É: tipologias de produto ("Sumos", "Talho", …) que agrupam artigos
-- diferentes da mesma família no separador 🧺 Stock e na Lista de Compras.
-- São duas tabelas GLOBAIS (sem evento_id — um produto é o mesmo em todos
-- os anos, a memória transita de festa para festa):
--
--   categorias         o dicionário (nome + descritivo). O DESCRITIVO é
--                      importante: segue no prompt do Gemini (fatura-ocr)
--                      para a AI categorizar bem os artigos novos — quanto
--                      melhor o descritivo, melhores as sugestões. Gerido
--                      pelo admin em Definições › Categorias de Artigos.
--
--   artigo_categorias  a memória artigo→categoria. A chave é o nome
--                      NORMALIZADO (minúsculas, sem acentos — o shopArtKey
--                      da app), por isso "Coca-Cola" e "coca-cola" são o
--                      mesmo artigo. origem='ai' marca o que a AI preencheu;
--                      'manual' o que foi definido/corrigido por pessoas.
--                      A AI só escreve com resolution=ignore-duplicates,
--                      logo NUNCA pisa o que já está definido.
--
-- Sem esta migração a app funciona à mesma: os fetch são tolerantes
-- (CATS_TABLE=false) e tudo o que é categorias fica simplesmente escondido.
-- =====================================================================

CREATE TABLE IF NOT EXISTS festasbv.categorias (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome        text NOT NULL UNIQUE,
  descritivo  text NOT NULL DEFAULT '',   -- exemplos/âmbito; vai no prompt da AI
  criado_em   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS festasbv.artigo_categorias (
  artigo_key    text PRIMARY KEY,          -- shopArtKey(artigo): minúsculas, sem acentos
  categoria_id  bigint NOT NULL REFERENCES festasbv.categorias(id) ON DELETE CASCADE,
  origem        text NOT NULL DEFAULT 'manual',   -- 'manual' | 'ai'
  atualizado_em timestamptz NOT NULL DEFAULT now()
);

-- Categorias iniciais (ON CONFLICT: correr de novo não duplica nem pisa
-- descritivos entretanto editados pelo admin na app)
INSERT INTO festasbv.categorias (nome, descritivo) VALUES
  ('Sumos',                'Refrigerantes e sumos sem álcool: Coca-Cola, Ice Tea, sumo de laranja, sumo de limão, néctares'),
  ('Águas',                'Água lisa ou com gás: garrafas, garrafões, packs'),
  ('Batatas Fritas',       'Batatas fritas de pacote e snacks afins: Lays, Ruffles, tortilhas, aperitivos'),
  ('Utensílios Refeição',  'Descartáveis e loiça para servir: pratos, copos, talheres, guardanapos, toalhas de mesa'),
  ('Talho',                'Carne fresca e para grelhar: acém, picanha, entremeada, frango, costeleta, enchidos'),
  ('Peixaria',             'Peixe e marisco: sardinha, carapau, bacalhau, camarão'),
  ('Bebidas Brancas',      'Bebidas espirituosas e licores: whisky, gin, vodka, rum, licor Beirão'),
  ('Cerveja/Sidra',        'Cerveja e sidra: barril, grades, latas, minis, Somersby'),
  ('Produtos Limpeza',     'Limpeza e higiene: detergentes, lixívia, esfregões, sacos do lixo, papel de cozinha'),
  ('Bricolagem',           'Material de obras e reparações: parafusos, fitas, tintas, ferramentas, iluminação'),
  ('Utensílios Churrasco', 'Material para o churrasco: carvão, pinhas, acendalhas, grelhas, espetos'),
  ('Sobremesas',           'Fruta, doces e sobremesas: leite condensado, natas, bolachas, gelados, melancia'),
  ('Entradas',             'Petiscos de entrada: queijos, patê de atum, pão, azeitonas, presunto, chouriço')
ON CONFLICT (nome) DO NOTHING;

-- GRANTs (sem isto: HTTP 403 / 42501)
GRANT ALL ON TABLE festasbv.categorias        TO anon, authenticated;
GRANT ALL ON TABLE festasbv.artigo_categorias TO anon, authenticated;

-- RLS
ALTER TABLE festasbv.categorias        ENABLE ROW LEVEL SECURITY;
ALTER TABLE festasbv.artigo_categorias ENABLE ROW LEVEL SECURITY;

-- categorias: todos os membros leem; só o admin gere o dicionário
DROP POLICY IF EXISTS categorias_sel   ON festasbv.categorias;
DROP POLICY IF EXISTS categorias_admin ON festasbv.categorias;

CREATE POLICY categorias_sel ON festasbv.categorias
  FOR SELECT TO authenticated
  USING (festasbv.is_allowed());

CREATE POLICY categorias_admin ON festasbv.categorias
  FOR ALL TO authenticated
  USING (festasbv.is_admin())
  WITH CHECK (festasbv.is_admin());

-- artigo_categorias: todos leem e podem PREENCHER buracos (é assim que a AI
-- grava sugestões quando qualquer membro importa uma fatura, e que um membro
-- categoriza um artigo novo ao criá-lo). MUDAR/limpar uma associação que já
-- existe é só do admin — a app respeita e o RLS garante.
DROP POLICY IF EXISTS artigo_categorias_sel   ON festasbv.artigo_categorias;
DROP POLICY IF EXISTS artigo_categorias_ins   ON festasbv.artigo_categorias;
DROP POLICY IF EXISTS artigo_categorias_admin ON festasbv.artigo_categorias;

CREATE POLICY artigo_categorias_sel ON festasbv.artigo_categorias
  FOR SELECT TO authenticated
  USING (festasbv.is_allowed());

CREATE POLICY artigo_categorias_ins ON festasbv.artigo_categorias
  FOR INSERT TO authenticated
  WITH CHECK (festasbv.is_allowed());

CREATE POLICY artigo_categorias_admin ON festasbv.artigo_categorias
  FOR ALL TO authenticated
  USING (festasbv.is_admin())
  WITH CHECK (festasbv.is_admin());
