-- =====================================================================
-- FestasBV — Migração: Filhos dos membros (festasbv.filhos +
-- festasbv.filho_presencas) e convidados-criança.
-- Correr no SQL Editor do Supabase (projeto festasbv).
-- É IDEMPOTENTE: pode ser corrido mais que uma vez sem erro.
-- Depende de: schema.sql -> functions.sql -> policies.sql.
--
-- O QUE É: as crianças NÃO pagam quota nenhuma — não entram em nenhuma
-- conta de dinheiro. Existem só para se saber QUANTAS bocas há em cada
-- refeição (compras, cozinha, mesas).
--
--   filhos            GLOBAL (sem evento_id, como conjuges/user_amigos):
--                     um filho é filho todos os anos. progenitor_a é
--                     obrigatório; progenitor_b fica NULL quando é um pai
--                     ou mãe solteiro/a. Gerido pelo admin em
--                     Definições › Utilizadores & Casais.
--
--   filho_presencas   POR EVENTO. Não tem coluna `modo` — de propósito:
--                     uma criança ou come ou não conta. A linha existe =
--                     come. Não há "só bebe" para crianças.
--
--   convidados.crianca  novo flag. Convidado-criança não paga (a app força
--                     pagante=false), mas conta para o total de bocas.
--
-- Sem esta migração a app funciona à mesma: os fetch são tolerantes
-- (FILHOS_TABLE=false) e tudo o que é crianças fica simplesmente escondido.
-- =====================================================================

CREATE TABLE IF NOT EXISTS festasbv.filhos (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome         text NOT NULL,
  progenitor_a text NOT NULL,          -- nome do membro (plantel)
  progenitor_b text,                   -- NULL = pai/mãe solteiro/a
  criado_em    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT filhos_progenitores_check CHECK (progenitor_b IS NULL OR progenitor_b <> progenitor_a)
);

-- Mesmo nome + mesmos pais não se repete (COALESCE porque NULL <> NULL)
CREATE UNIQUE INDEX IF NOT EXISTS filhos_nome_pais_idx
  ON festasbv.filhos (nome, progenitor_a, COALESCE(progenitor_b, ''));

CREATE TABLE IF NOT EXISTS festasbv.filho_presencas (
  id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  filho_id  bigint NOT NULL REFERENCES festasbv.filhos(id)  ON DELETE CASCADE,
  evento_id bigint NOT NULL REFERENCES festasbv.eventos(id) ON DELETE CASCADE,
  dia       text NOT NULL,
  ref       text NOT NULL,
  CONSTRAINT filho_presencas_unq UNIQUE (filho_id, evento_id, dia, ref)
);

CREATE INDEX IF NOT EXISTS filho_presencas_evento_idx ON festasbv.filho_presencas (evento_id);
CREATE INDEX IF NOT EXISTS filho_presencas_filho_idx  ON festasbv.filho_presencas (filho_id);

-- Convidados: flag de criança (não paga, mas conta para as bocas)
ALTER TABLE festasbv.convidados
  ADD COLUMN IF NOT EXISTS crianca boolean NOT NULL DEFAULT false;

-- ---------------------------------------------------------------------
-- Função de apoio ao RLS: este filho é do meu agregado?
-- SECURITY DEFINER pelo mesmo motivo de meu_amigo(): precisa de ler
-- user_amigos/conjuges para lá do RLS.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION festasbv.filho_meu(p_filho_id bigint)
  RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER
  SET search_path TO 'festasbv', 'public'
AS $$
  WITH meu AS (
    SELECT amigo FROM festasbv.user_amigos WHERE email = auth.email()
  ), meus AS (
    SELECT amigo FROM meu
    UNION SELECT c.amigo_b FROM festasbv.conjuges c JOIN meu m ON c.amigo_a = m.amigo
    UNION SELECT c.amigo_a FROM festasbv.conjuges c JOIN meu m ON c.amigo_b = m.amigo
  )
  SELECT EXISTS (
    SELECT 1 FROM festasbv.filhos f
    WHERE f.id = p_filho_id
      AND (f.progenitor_a IN (SELECT amigo FROM meus)
        OR f.progenitor_b IN (SELECT amigo FROM meus))
  );
$$;

-- GRANTs (sem isto: HTTP 403 / 42501)
GRANT ALL ON TABLE festasbv.filhos          TO anon, authenticated;
GRANT ALL ON TABLE festasbv.filho_presencas TO anon, authenticated;

ALTER TABLE festasbv.filhos          ENABLE ROW LEVEL SECURITY;
ALTER TABLE festasbv.filho_presencas ENABLE ROW LEVEL SECURITY;

-- filhos: todos os membros leem; só o admin parametriza (é no painel dele)
DROP POLICY IF EXISTS filhos_sel   ON festasbv.filhos;
DROP POLICY IF EXISTS filhos_admin ON festasbv.filhos;

CREATE POLICY filhos_sel ON festasbv.filhos
  FOR SELECT TO authenticated
  USING (festasbv.is_allowed());

CREATE POLICY filhos_admin ON festasbv.filhos
  FOR ALL TO authenticated
  USING (festasbv.is_admin())
  WITH CHECK (festasbv.is_admin());

-- filho_presencas: mesmas regras das presenças dos pais — cada agregado
-- marca as dos seus filhos enquanto o dia estiver aberto; o admin marca tudo.
DROP POLICY IF EXISTS filho_presencas_sel      ON festasbv.filho_presencas;
DROP POLICY IF EXISTS filho_presencas_admin    ON festasbv.filho_presencas;
DROP POLICY IF EXISTS filho_presencas_self_ins ON festasbv.filho_presencas;
DROP POLICY IF EXISTS filho_presencas_self_del ON festasbv.filho_presencas;

CREATE POLICY filho_presencas_sel ON festasbv.filho_presencas
  FOR SELECT TO authenticated
  USING (festasbv.is_allowed());

CREATE POLICY filho_presencas_admin ON festasbv.filho_presencas
  FOR ALL TO authenticated
  USING (festasbv.is_admin())
  WITH CHECK (festasbv.is_admin());

CREATE POLICY filho_presencas_self_ins ON festasbv.filho_presencas
  FOR INSERT TO authenticated
  WITH CHECK (festasbv.is_allowed()
    AND festasbv.filho_meu(filho_id)
    AND festasbv.dia_aberto_evento(evento_id, dia));

CREATE POLICY filho_presencas_self_del ON festasbv.filho_presencas
  FOR DELETE TO authenticated
  USING (festasbv.is_allowed()
    AND festasbv.filho_meu(filho_id)
    AND festasbv.dia_aberto_evento(evento_id, dia));
