-- =====================================================================
-- FestasBV — Migração: Pagamentos de dívida à espera de validação
-- (festasbv.pagamentos_pendentes)
-- Correr no SQL Editor do Supabase (projeto festasbv).
-- É IDEMPOTENTE: pode ser corrido mais que uma vez sem erro.
-- Depende de: schema.sql -> functions.sql -> policies.sql.
--
-- O QUE É: registar um pagamento de dívida era só do admin, porque um
-- pagamento mexe nas contas de toda a gente (a tabela `pagamentos` só
-- aceita escrita de is_admin(), e a app grava-a a substituir o ano
-- inteiro). Quem pagava tinha de avisar o admin por fora da app.
--
-- Esta tabela é a CAIXA DE ENTRADA desses pagamentos: o membro declara o
-- que pagou (dele ou do cônjuge) e a linha fica aqui, à espera. Nada disto
-- entra no calcular() — enquanto estiver aqui, não é dinheiro, é um aviso.
-- Quando o admin aprova, a app cria o cash-flow verdadeiro em `pagamentos`
-- (é ele que tem a permissão) e marca esta linha como 'aprovado'.
--
-- O QUE FICA GUARDADO É O QUE FOI PEDIDO, não o que se calcula na hora: as
-- dívidas mudam com as despesas que forem entrando, e o admin tem de poder
-- ver e aprovar exatamente o que a pessoa declarou.
--   valor  = a dívida que o pagamento salda
--   extra  = arredondamento para cima que vai para a poupança (como em
--            `pagamentos.extra`); o dinheiro entregue é valor + extra
--   ref    = as mesmas chaves 'own:Nome' / 'conv:Nome' dos pagamentos, para
--            a aprovação copiar sem traduzir nada. Vazio = adiantamento.
--
-- ESTADOS: 'pendente' -> 'aprovado' | 'rejeitado'. Só o admin decide (a
-- policy de UPDATE é só dele). O membro pode apagar enquanto não estiver
-- aprovado — cancelar o que pediu por engano, ou tirar da vista um pedido
-- rejeitado. Aprovado não se apaga: já virou cash-flow, e apagar aqui
-- deixava o pagamento real órfão de explicação.
--
-- Sem esta migração a app funciona à mesma: o fetch é tolerante
-- (PAGPEND_TABLE=false), a opção "Pagar Dívida" volta a ser só do admin e
-- o resto fica escondido.
-- =====================================================================

CREATE TABLE IF NOT EXISTS festasbv.pagamentos_pendentes (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  evento_id         bigint NOT NULL REFERENCES festasbv.eventos(id) ON DELETE CASCADE,
  de                text   NOT NULL,                    -- quem pagou (membro)
  para              text   NOT NULL DEFAULT '',         -- tesoureiro à data do pedido
  valor             numeric(10,2) NOT NULL,             -- dívida saldada
  extra             numeric(10,2) NOT NULL DEFAULT 0,   -- arredondamento p/ poupança
  ref               text   NOT NULL DEFAULT '',         -- 'own:Nome, conv:Nome' (vazio = adiantamento)
  data              date,                               -- quando foi pago, diz quem pagou
  nota              text   NOT NULL DEFAULT '',         -- "MB Way", "em mão no jantar"…
  estado            text   NOT NULL DEFAULT 'pendente', -- 'pendente' | 'aprovado' | 'rejeitado'
  criado_por        text   NOT NULL DEFAULT '',         -- nome do amigo que submeteu
  criado_por_email  text   NOT NULL DEFAULT '',
  criado_em         timestamptz NOT NULL DEFAULT now(),
  decidido_por      text,                               -- email de quem decidiu (admin)
  decidido_em       timestamptz,
  motivo            text,                               -- razão da rejeição, para quem pediu
  CONSTRAINT pagamentos_pendentes_estado_chk
    CHECK (estado IN ('pendente','aprovado','rejeitado')),
  CONSTRAINT pagamentos_pendentes_valor_chk CHECK (valor > 0 AND extra >= 0)
);

CREATE INDEX IF NOT EXISTS pagamentos_pendentes_evento_idx
  ON festasbv.pagamentos_pendentes (evento_id);

-- GRANTs (sem isto: HTTP 403 / 42501)
GRANT ALL ON TABLE festasbv.pagamentos_pendentes TO anon, authenticated;

ALTER TABLE festasbv.pagamentos_pendentes ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------
-- Guarda de inserção: o que a app manda no pedido não decide nada.
-- Um pedido nasce SEMPRE 'pendente', sem decisão, e assinado por quem o
-- fez — senão bastava um POST com estado='aprovado' para saltar a fila
-- (a linha não entrava nas contas, mas aparecia aprovada a toda a gente).
-- O admin continua a poder escrever o que quiser: é ele que aprova.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION festasbv.pagpend_guard_ins()
  RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER
  SET search_path TO 'festasbv', 'public'
AS $$
BEGIN
  IF NOT festasbv.is_admin() THEN
    NEW.estado       := 'pendente';
    NEW.decidido_por := NULL;
    NEW.decidido_em  := NULL;
    NEW.motivo       := NULL;
  END IF;
  NEW.criado_por_email := COALESCE(auth.email(), '');
  NEW.criado_em        := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS pagamentos_pendentes_guard_ins ON festasbv.pagamentos_pendentes;
CREATE TRIGGER pagamentos_pendentes_guard_ins
  BEFORE INSERT ON festasbv.pagamentos_pendentes
  FOR EACH ROW EXECUTE FUNCTION festasbv.pagpend_guard_ins();

-- ---------------------------------------------------------------------
-- Policies
--   sel      admin vê tudo; o membro vê os seus (e os do cônjuge)
--   self_ins qualquer membro pede, mas só por si ou pelo cônjuge
--   self_del cancela / tira da vista enquanto não estiver aprovado
--   admin    tudo (é ele que aprova, rejeita e limpa)
-- Não há policy de UPDATE para o membro de propósito: mudar o valor de um
-- pedido depois de o admin o ter visto é reescrever o que ele aprovou.
-- Quem se enganou apaga e pede outra vez.
-- ---------------------------------------------------------------------
DROP POLICY IF EXISTS pagamentos_pendentes_sel      ON festasbv.pagamentos_pendentes;
DROP POLICY IF EXISTS pagamentos_pendentes_self_ins ON festasbv.pagamentos_pendentes;
DROP POLICY IF EXISTS pagamentos_pendentes_self_del ON festasbv.pagamentos_pendentes;
DROP POLICY IF EXISTS pagamentos_pendentes_admin    ON festasbv.pagamentos_pendentes;

CREATE POLICY pagamentos_pendentes_sel ON festasbv.pagamentos_pendentes
  FOR SELECT TO authenticated
  USING (festasbv.is_allowed()
    AND (festasbv.is_admin() OR festasbv.meu_amigo(de)));

CREATE POLICY pagamentos_pendentes_self_ins ON festasbv.pagamentos_pendentes
  FOR INSERT TO authenticated
  WITH CHECK (festasbv.is_allowed() AND festasbv.meu_amigo(de));

CREATE POLICY pagamentos_pendentes_self_del ON festasbv.pagamentos_pendentes
  FOR DELETE TO authenticated
  USING (festasbv.is_allowed()
    AND festasbv.meu_amigo(de)
    AND estado <> 'aprovado');

CREATE POLICY pagamentos_pendentes_admin ON festasbv.pagamentos_pendentes
  FOR ALL TO authenticated
  USING (festasbv.is_admin())
  WITH CHECK (festasbv.is_admin());
