-- =====================================================================
-- FestasBV — Migração: Lista de Compras (festasbv.shoplist)
-- Correr UMA VEZ no SQL Editor do Supabase (projeto festasbv).
-- Depende de: schema.sql (eventos) e functions.sql (is_allowed/is_admin).
-- Ordem: schema.sql -> functions.sql -> policies.sql -> ESTE ficheiro.
--
-- NOTA sobre IDs: ao contrário das tabelas legadas, esta usa IDENTITY,
-- por isso a app pode inserir SEM id (a BD atribui) e ler o id de volta,
-- que é exatamente como o resto da app já trabalha (return=representation).
-- =====================================================================

CREATE TABLE IF NOT EXISTS festasbv.shoplist (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  evento_id    bigint  NOT NULL,
  artigo       text    NOT NULL,
  quantidade   text    NOT NULL DEFAULT '',
  tipo         text    NOT NULL,                 -- Gerais/Bebidas/Almoço/Jantar/Renda/Cerveja
  data_valor   date,                             -- só p/ Almoço/Jantar: a que refeição se destina
  estado       text    NOT NULL DEFAULT 'pendente',  -- 'pendente' | 'comprado'
  tratado_por  text,                             -- nome do membro que "vai tratar"
  no_carrinho  boolean NOT NULL DEFAULT false,   -- já no carrinho durante as compras
  compra_id    text,                             -- token partilhado pelos artigos da mesma ida às compras
  cf_desc      text,                             -- descritivo do cash-flow associado (apresentação)
  valor        numeric(10,2),                    -- fatia alocada ao grupo (opcional, informativo)
  criado_por   text    NOT NULL DEFAULT '',      -- quem adicionou o artigo (nome do membro)
  criado_em    timestamptz NOT NULL DEFAULT now(),
  comprado_em  timestamptz,
  CONSTRAINT shoplist_evento_id_fkey FOREIGN KEY (evento_id)
    REFERENCES festasbv.eventos(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS shoplist_evento_idx ON festasbv.shoplist (evento_id);

-- GRANTs (sem isto: HTTP 403 / 42501)
GRANT ALL ON TABLE festasbv.shoplist TO anon, authenticated;

-- RLS
ALTER TABLE festasbv.shoplist ENABLE ROW LEVEL SECURITY;

-- Lista partilhada: qualquer membro autorizado vê e edita (adicionar, marcar
-- "eu trato", pôr no carrinho, registar como comprado, remover). Admin tudo.
CREATE POLICY shoplist_sel ON festasbv.shoplist
  FOR SELECT TO authenticated
  USING (festasbv.is_allowed());

CREATE POLICY shoplist_ins ON festasbv.shoplist
  FOR INSERT TO authenticated
  WITH CHECK (festasbv.is_allowed());

CREATE POLICY shoplist_upd ON festasbv.shoplist
  FOR UPDATE TO authenticated
  USING (festasbv.is_allowed())
  WITH CHECK (festasbv.is_allowed());

CREATE POLICY shoplist_del ON festasbv.shoplist
  FOR DELETE TO authenticated
  USING (festasbv.is_allowed());

CREATE POLICY shoplist_admin ON festasbv.shoplist
  FOR ALL TO authenticated
  USING (festasbv.is_admin())
  WITH CHECK (festasbv.is_admin());
