-- =====================================================================
-- FestasBV — Migração: Stock por refeição (festasbv.stock_lotes)
-- Correr no SQL Editor do Supabase (projeto festasbv).
-- É IDEMPOTENTE: pode ser corrido mais que uma vez sem erro.
-- Depende de: schema.sql (eventos) e functions.sql (is_allowed/is_admin).
-- Ordem: schema.sql -> functions.sql -> policies.sql -> shoplist.sql -> ESTE.
--
-- O QUE É: artigos comprados que se repartem por várias refeições (ou por
-- tipos de despesa) são registados como LOTES: quantidade + preço por artigo.
-- O valor do lote entra numa linha "🧺 Stock" (Gerais) da compra; a app move
-- depois o alocado para as refeições/tipos via o campo `alocacoes` (JSON),
-- sem nunca reescrever as despesas reais.
--
-- `alocacoes` é um array JSON de entradas:
--   { "tipo": "Almoço"|"Jantar", "data": "YYYY-MM-DD", "qtd": <número> }  -> refeição
--   { "tipo": "Gerais"|"Bebidas"|"Cerveja"|"Renda", "data": null, "qtd": <número> } -> tipo puro
-- O que não estiver alocado fica na bolsa comum (Gerais). Como é JSON, mover
-- artigos entre refeições/tipos no separador 🧺 Stock NÃO precisa de migração.
--
-- NOTA sobre IDs: usa IDENTITY (como a shoplist), por isso a app insere SEM id
-- e lê o id de volta (return=representation).
--
-- Sem esta tabela a app funciona à mesma: o fetch de stock_lotes é tolerante
-- (STOCK_TABLE=false) e toda a parte de stock fica simplesmente escondida.
-- =====================================================================

CREATE TABLE IF NOT EXISTS festasbv.stock_lotes (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  evento_id    bigint  NOT NULL,
  compra_id    text,                              -- token da compra (liga às despesas)
  artigo       text    NOT NULL,
  qtd          numeric NOT NULL DEFAULT 0,        -- quantidade do lote (na unidade)
  unidade      text    NOT NULL DEFAULT '',       -- kg/L/un/pacote/… ('' = sem unidade)
  valor        numeric(10,2) NOT NULL DEFAULT 0,  -- preço pago pelo lote
  alocacoes    jsonb   NOT NULL DEFAULT '[]'::jsonb,  -- [{tipo,data,qtd}] (ver acima)
  criado_em    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT stock_lotes_evento_id_fkey FOREIGN KEY (evento_id)
    REFERENCES festasbv.eventos(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS stock_lotes_evento_idx ON festasbv.stock_lotes (evento_id);
CREATE INDEX IF NOT EXISTS stock_lotes_compra_idx ON festasbv.stock_lotes (compra_id);

-- Instalações anteriores ao CREATE TABLE já ter todas as colunas (idempotente).
ALTER TABLE festasbv.stock_lotes ADD COLUMN IF NOT EXISTS compra_id text;
ALTER TABLE festasbv.stock_lotes ADD COLUMN IF NOT EXISTS unidade   text NOT NULL DEFAULT '';
ALTER TABLE festasbv.stock_lotes ADD COLUMN IF NOT EXISTS alocacoes jsonb NOT NULL DEFAULT '[]'::jsonb;

-- GRANTs (sem isto: HTTP 403 / 42501)
GRANT ALL ON TABLE festasbv.stock_lotes TO anon, authenticated;

-- RLS — mesmo modelo partilhado da shoplist: qualquer membro autorizado vê e
-- escreve (registar uma compra insere lotes; a app é que limita a edição de
-- alocações ao admin na UI). Admin tudo.
ALTER TABLE festasbv.stock_lotes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS stock_lotes_sel   ON festasbv.stock_lotes;
DROP POLICY IF EXISTS stock_lotes_ins   ON festasbv.stock_lotes;
DROP POLICY IF EXISTS stock_lotes_upd   ON festasbv.stock_lotes;
DROP POLICY IF EXISTS stock_lotes_del   ON festasbv.stock_lotes;
DROP POLICY IF EXISTS stock_lotes_admin ON festasbv.stock_lotes;

CREATE POLICY stock_lotes_sel ON festasbv.stock_lotes
  FOR SELECT TO authenticated
  USING (festasbv.is_allowed());

CREATE POLICY stock_lotes_ins ON festasbv.stock_lotes
  FOR INSERT TO authenticated
  WITH CHECK (festasbv.is_allowed());

CREATE POLICY stock_lotes_upd ON festasbv.stock_lotes
  FOR UPDATE TO authenticated
  USING (festasbv.is_allowed())
  WITH CHECK (festasbv.is_allowed());

CREATE POLICY stock_lotes_del ON festasbv.stock_lotes
  FOR DELETE TO authenticated
  USING (festasbv.is_allowed());

CREATE POLICY stock_lotes_admin ON festasbv.stock_lotes
  FOR ALL TO authenticated
  USING (festasbv.is_admin())
  WITH CHECK (festasbv.is_admin());
