-- =====================================================================
-- FestasBV — Migração: Encomenda de T-shirts (festasbv.tshirt_tamanhos +
-- festasbv.tshirts).
-- Correr no SQL Editor do Supabase (projeto festasbv).
-- É IDEMPOTENTE: pode ser corrido mais que uma vez sem erro.
-- Depende de: schema.sql -> functions.sql -> policies.sql.
--
-- O QUE É: centralizar os pedidos de t-shirts das Festas. Cada pessoa
-- adiciona as t-shirts que quer encomendar — uma linha por t-shirt, com o
-- NOME de quem a vai vestir, a TIPOLOGIA (Homem/Mulher/Criança) e o
-- TAMANHO. O admin parametriza que tamanhos existem para cada tipologia
-- (e, opcionalmente, o preço) em Definições › T-shirts.
--
--   tshirt_tamanhos   GLOBAL (sem evento_id, como conjuges/filhos): é a
--                     grelha de tamanhos disponíveis. `preco` fica a 0
--                     enquanto o admin não o definir — a app só mostra
--                     dinheiro quando há algum preço > 0.
--
--   tshirts           POR EVENTO (uma encomenda por ano). `tamanho` é
--                     TEXTO, não FK: apagar um tamanho da grelha não
--                     apaga nem corrompe encomendas já feitas.
--
-- NADA DISTO ENTRA NAS CONTAS. As t-shirts não mexem em quotas, saldos
-- nem cash-flows — é só o levantamento dos pedidos.
--
-- Sem esta migração a app funciona à mesma: os fetch são tolerantes
-- (TSHIRTS_TABLE=false) e o separador 👕 fica simplesmente escondido.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Grelha de tamanhos (parametrização do admin)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS festasbv.tshirt_tamanhos (
  id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo      text NOT NULL,                       -- 'Homem' | 'Mulher' | 'Criança'
  tamanho   text NOT NULL,                       -- 'S', 'M', 'L', '8 anos', …
  ordem     int  NOT NULL DEFAULT 0,             -- ordem de apresentação dentro da tipologia
  preco     numeric(10,2) NOT NULL DEFAULT 0,    -- 0 = ainda sem preço definido
  criado_em timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT tshirt_tamanhos_tipo_check CHECK (tipo IN ('Homem','Mulher','Criança'))
);

-- O mesmo tamanho não se repete dentro da mesma tipologia
CREATE UNIQUE INDEX IF NOT EXISTS tshirt_tamanhos_unq
  ON festasbv.tshirt_tamanhos (tipo, tamanho);

-- Instalações anteriores ao CREATE TABLE já ter todas as colunas (idempotente)
ALTER TABLE festasbv.tshirt_tamanhos ADD COLUMN IF NOT EXISTS ordem int NOT NULL DEFAULT 0;
ALTER TABLE festasbv.tshirt_tamanhos ADD COLUMN IF NOT EXISTS preco numeric(10,2) NOT NULL DEFAULT 0;

-- ---------------------------------------------------------------------
-- Encomendas (uma linha = uma t-shirt)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS festasbv.tshirts (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  evento_id  bigint NOT NULL REFERENCES festasbv.eventos(id) ON DELETE CASCADE,
  membro     text NOT NULL,                      -- membro do plantel que encomenda (quem paga/entrega)
  nome       text NOT NULL,                      -- nome de quem veste a t-shirt
  tipo       text NOT NULL,                      -- 'Homem' | 'Mulher' | 'Criança'
  tamanho    text NOT NULL,                      -- texto livre vindo da grelha (não é FK, de propósito)
  criado_por text,                               -- email de quem registou (auditoria)
  criado_em  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT tshirts_tipo_check CHECK (tipo IN ('Homem','Mulher','Criança'))
);

CREATE INDEX IF NOT EXISTS tshirts_evento_idx ON festasbv.tshirts (evento_id);
CREATE INDEX IF NOT EXISTS tshirts_membro_idx ON festasbv.tshirts (membro);

-- GRANTs (sem isto: HTTP 403 / 42501)
GRANT ALL ON TABLE festasbv.tshirt_tamanhos TO anon, authenticated;
GRANT ALL ON TABLE festasbv.tshirts         TO anon, authenticated;

ALTER TABLE festasbv.tshirt_tamanhos ENABLE ROW LEVEL SECURITY;
ALTER TABLE festasbv.tshirts         ENABLE ROW LEVEL SECURITY;

-- tamanhos: todos os membros leem; só o admin parametriza (é no painel dele)
DROP POLICY IF EXISTS tshirt_tamanhos_sel   ON festasbv.tshirt_tamanhos;
DROP POLICY IF EXISTS tshirt_tamanhos_admin ON festasbv.tshirt_tamanhos;

CREATE POLICY tshirt_tamanhos_sel ON festasbv.tshirt_tamanhos
  FOR SELECT TO authenticated
  USING (festasbv.is_allowed());

CREATE POLICY tshirt_tamanhos_admin ON festasbv.tshirt_tamanhos
  FOR ALL TO authenticated
  USING (festasbv.is_admin())
  WITH CHECK (festasbv.is_admin());

-- encomendas: toda a gente vê a lista (é uma encomenda de grupo), mas cada
-- um só mexe nas suas (as do próprio e as do cônjuge, via meu_amigo()).
-- O admin mexe em tudo.
DROP POLICY IF EXISTS tshirts_sel      ON festasbv.tshirts;
DROP POLICY IF EXISTS tshirts_admin    ON festasbv.tshirts;
DROP POLICY IF EXISTS tshirts_self_ins ON festasbv.tshirts;
DROP POLICY IF EXISTS tshirts_self_upd ON festasbv.tshirts;
DROP POLICY IF EXISTS tshirts_self_del ON festasbv.tshirts;

CREATE POLICY tshirts_sel ON festasbv.tshirts
  FOR SELECT TO authenticated
  USING (festasbv.is_allowed());

CREATE POLICY tshirts_admin ON festasbv.tshirts
  FOR ALL TO authenticated
  USING (festasbv.is_admin())
  WITH CHECK (festasbv.is_admin());

CREATE POLICY tshirts_self_ins ON festasbv.tshirts
  FOR INSERT TO authenticated
  WITH CHECK (festasbv.is_allowed() AND festasbv.meu_amigo(membro));

CREATE POLICY tshirts_self_upd ON festasbv.tshirts
  FOR UPDATE TO authenticated
  USING (festasbv.is_allowed() AND festasbv.meu_amigo(membro))
  WITH CHECK (festasbv.is_allowed() AND festasbv.meu_amigo(membro));

CREATE POLICY tshirts_self_del ON festasbv.tshirts
  FOR DELETE TO authenticated
  USING (festasbv.is_allowed() AND festasbv.meu_amigo(membro));

-- ---------------------------------------------------------------------
-- Arranque opcional: grelha de tamanhos típica. Comenta/ajusta à vontade —
-- o admin edita tudo isto em Definições › T-shirts.
-- ---------------------------------------------------------------------
INSERT INTO festasbv.tshirt_tamanhos (tipo, tamanho, ordem)
VALUES
  ('Homem','S',1),('Homem','M',2),('Homem','L',3),('Homem','XL',4),('Homem','XXL',5),
  ('Mulher','S',1),('Mulher','M',2),('Mulher','L',3),('Mulher','XL',4),
  ('Criança','4 anos',1),('Criança','6 anos',2),('Criança','8 anos',3),('Criança','10 anos',4),('Criança','12 anos',5)
ON CONFLICT (tipo, tamanho) DO NOTHING;
